# @package model
_target_: project.utils.config.ModelConfig

version: v0
input_size: 10
hidden_size: 64
output_size: 10
n_g_layers: 1
n_r_layers: 1
n_o_layers: 1
gate_noise_level: 1.0
batch_first: true